version: "3.5"

services:
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  server:
    build: ./server
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    image: rails:dev
    volumes:
      - ./server:/app
      - ./server/vendor/bundle:/app/vendor/bundle
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
    ports:
      - 3000:3000
    depends_on:
      - db
  client:
    build: ./client
    command: yarn start
    volumes:
      - ./client:/app
    ports:
      - 8000:3000
volumes:
  postgres-data:
    driver: local
